runtime: python27
# env: flex;
# entrypoint: gunicorn -b :$PORT main:appengine
#
# runtime_config:
#     python_version: 3
api_version: 1
threadsafe: true

handlers:
# - url: /stylesheet
#   static_dir: stylesheet
# - url: /templates
#   static_dir: templates
#   application_readable: true
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
- name: ssl
  version: "latest"
